version: 0.2

        
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  build:
    commands: 
      - python Helper_Functions/ipynb_to_py.py --input_file Pipelines/Training/Pipeline_Training.ipynb --output_file Pipeline_Training.py
      - python Pipeline_Training.py   
      - python Helper_Functions/ipynb_to_py.py --input_file Pipelines/Scoring/Pipeline_Scoring.ipynb --output_file Pipeline_Scoring.py
      - python Pipeline_Scoring.py
  post_build:
    commands: 
      - cd Endpoint/Function_Contents/
      - zip -r Lambda_Code.zip .
      - aws s3 cp Lambda_Code.zip s3://demo-inputs-bucket/Lambda/Lambda_Code.zip
  
artifacts:
  files:
    - '**/*'